services:
  wicap-assist-live:
    profiles: ["observe"]
    build: .
    network_mode: host
    environment:
      - WICAP_REPO_ROOT=/wicap
    volumes:
      - ./data:/app/data
      # Host WiCAP repo path. Defaults to a sibling checkout at ../wicap for portable rollouts.
      - ${WICAP_HOST_REPO_ROOT:-../wicap}:/wicap:ro
    command: ["live", "--interval", "10", "--control-mode", "observe"]
    restart: unless-stopped

  wicap-assist-control:
    profiles: ["control"]
    build: .
    network_mode: host
    environment:
      - WICAP_REPO_ROOT=/wicap
    volumes:
      - ./data:/app/data
      - ${WICAP_HOST_REPO_ROOT:-../wicap}:/wicap
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      [
        "live",
        "--interval",
        "10",
        "--control-mode",
        "assist",
        "--control-check-threshold",
        "2",
        "--control-recover-threshold",
        "4",
      ]
    restart: unless-stopped

  wicap-assist:
    profiles: ["control"]
    build: .
    network_mode: host
    environment:
      - WICAP_REPO_ROOT=/wicap
    volumes:
      - ./data:/app/data
      - ${WICAP_HOST_REPO_ROOT:-../wicap}:/wicap
      - /var/run/docker.sock:/var/run/docker.sock
    stdin_open: true
    tty: true

  wicap-assist-scheduler:
    profiles: ["scheduler", "hybrid"]
    build: .
    network_mode: host
    environment:
      - WICAP_REPO_ROOT=/wicap
      - WICAP_ASSIST_MEMORY_BACKEND=${WICAP_ASSIST_MEMORY_BACKEND:-sqlite}
    volumes:
      - ./data:/app/data
      - ${WICAP_HOST_REPO_ROOT:-../wicap}:/wicap:ro
    command:
      [
        "memory-maintenance",
        "--lookback-days",
        "14",
        "--stale-days",
        "7",
        "--max-recent-transitions",
        "24",
        "--prune-stale",
      ]
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    profiles: ["hybrid"]
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    ports:
      - "6379:6379"
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant:v1.11.1
    profiles: ["hybrid"]
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./data/qdrant:/qdrant/storage
    restart: unless-stopped
